### ISSUE TITLE
...stuck??

### ISSUE THREAD

**Issue by buzzijavier** [joaoricardo000/whatsapp-bot-seed#1]
INFO:root:Starting....
INFO:yowsup.layers.axolotl.layer:Axolotl layer is generating keys
INFO:root:Starting....

Doesnt move from there.

**Comment by joaoricardo000** [comment]
The logging is not very helpful, but after the "Starting..." the server has started ok!  
Did you tried to send a message?

**Comment by KarimJedda** [comment]
tried it, it works fine :+1:

**Comment by buzzijavier** [comment]
NM. Now it works...
