### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by Sunil02324** [joaoricardo000/whatsapp-bot-seed#14]
I have installed all requirements and has started the server. 
A continous loop was running with server restarting again and again. It continued for some time and then it stop (see picture given below)
http://i.imgur.com/Mz3Ybo1.png

I tried to message to that number from whatsapp but there was no reply. it is not even showing as online. Messages are also not delivered. I am running this on my Ubuntu 14.04 VPS.

**Comment by joaoricardo000** [comment]
This is a problem with yowsup, soon to be added on pip.
To fix it check this: https://github.com/tgalal/yowsup/issues/1164

Edit yowsup/env/env_s40.py

Change from:

class S40YowsupEnv(YowsupEnv):
 _VERSION = "2.12.96"
 _OS_NAME= "S40"
 _OS_VERSION = "14.26"
 _DEVICE_NAME = "Nokia302"
 _TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1439921717185{phone}"
 _AXOLOTL = True

to

class S40YowsupEnv(YowsupEnv):
 _VERSION = "2.13.5"
 _OS_NAME= "S40"
 _OS_VERSION = "14.26"
 _DEVICE_NAME = "Nokia302"
 _TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1442277896714{phone}"
 _AXOLOTL = True

**Comment by JeffSaa** [comment]
I have the same issue. I change my yowsup/env/env_s40.py like this but a I have a not-authorized then I edit:
_VERSION = "2.16.11"
_TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"
And say me: unexpected indent.
