### ISSUE TITLE
Error, help please

### ISSUE THREAD

**Issue by LeexModz** [joaoricardo000/whatsapp-bot-seed#16]
When i use the command "sudo yowsup-cli demos -l (Number):(Pwd)= -y" I get this error in the terminal " ERROR:yowsup.layers.axolot1.layer : No valid sessionsBad Mac!   " I dont know why it happened, before that it works properly, help please ;)

**Comment by LeexModz** [comment]
*After use /L

**Comment by bergonzzi** [comment]
I also had this issue before but only for a specific number. I solved by logging into yowsup like you did:

`sudo yowsup-cli demos -l (Number):(Pwd)= -y`

followed by `/L` to login and then I sent a message directly to the problematic number with `/message send [number] "test message"`. This apparently creates a new session with this number and from then on it works.

**Comment by LeexModz** [comment]
ERROR:yowsup.layers.axolotl.layer:No valid sessionsOver 2000 messages into
the future!


I receive this error when i send the message; and i dont receive the message


2015-12-29 2:46 GMT+01:00 André Bergonse <notifications@github.com>:

**Comment by thundergreen** [comment]
I'm facing the same issue. some ideas?

**Comment by joaoricardo000** [comment]
Sometimes I get this error too, but usually the bot continues to work with no problem.
The magic to make everything work again is deleting the ~/.yowsup/<phonenumber> folder and restarting the bot.
To have more info about this especific error, check https://github.com/tgalal/yowsup/issues
