### ISSUE TITLE
Status message

### ISSUE THREAD

**Issue by luckyz** [joaoricardo000/whatsapp-bot-seed#20]
How can I set an status message when server starts?

**Comment by joaoricardo000** [comment]
Check out the yowsup lib. All messages are implemented there, and most of it you can use with the console.
https://github.com/tgalal/yowsup/wiki/yowsup-cli-2.0

Right now the bot does not handle this kind of messages.

**Comment by x23piracy** [comment]
Hi,

well while the bot cannot handle this actualy is it possible to configure yowsup itself with the same credentials your bot is using while both the bot and yowsup is used together? afaik there can be only one client online at the same time with same credentials. Else we may risk our account?!
