### ISSUE TITLE
How to add a trigger to an external event and send a msg

### ISSUE THREAD

**Issue by joyarzun** [joaoricardo000/whatsapp-bot-seed#23]
Hi there.
I want to add an external event and this trigger a message by WA. The external event is other python process that has motion detection. So, when it detects motion this should trigger a msg to whatsapp-bot. In your project, the event is a message received that trigger a response. In a wider context, I have a raspberry pi with a cam. I want that RPI send me a message if the cam detect motion. How I can accomplish this?  Any advice or help are grateful

**Comment by x23piracy** [comment]
Hi,

yes it would be really nice to have the possibility to trigger a python script or something while the bot is running to tell him send this or that to some contact.

Is this already possible?

Regards X23

**Comment by joaoricardo000** [comment]
Hi!

To achieve this I used messaging with RabbitMQ.
I created a new layer that listened to a queue that receives stomp messages with the phone number and message as parameters, and just send it.

That is the Layer code:
```python
import threading
import pika
import config
import simplejson
from yowsup.layers.interface import YowInterfaceLayer
from yowsup.layers.protocol_messages.protocolentities.message_text import TextMessageProtocolEntity


class RabbitMQLayer(YowInterfaceLayer):
    def __init__(self):
        super(RabbitMQLayer, self).__init__()
        self.connection = pika.BlockingConnection(pika.ConnectionParameters(config.rabbitmq["host"]))
        self.stomp_channel_service = self.connection.channel()
        self.queue_name = "queue/whatsapp/message/send/request"
        threading.Thread(target=self.listen_queue, args=()).start()

    def on_message_request(self, ch, method, properties, body):
        ch.basic_ack(delivery_tag=method.delivery_tag)
        message = simplejson.loads(body)
        self.toLower(TextMessageProtocolEntity(message["body"].encode("UTF-8"), to=message["to"]))

    def listen_queue(self):
        self.stomp_channel_service.queue_declare(queue=self.queue_name, durable=True)
        self.stomp_channel_service.basic_consume(self.on_message_request, queue=self.queue_name)
        self.stomp_channel_service.start_consuming()
```

And just add the layer on server.py
```python
stack_builder.push(YowParallelLayer([RouteLayer, NotificationsLayer, RabbitMQLayer]))
```


With this layer working on the bot, any message sent to this queue with "body" and "to", will send a whatsapp message.

A simple python script that sends a stomp message looks like this:

```python
import pika

connection = pika.BlockingConnection(pika.ConnectionParameters('localhost'))
channel_service = connection.channel()
channel_service.basic_publish(
            exchange='',
            routing_key="queue/whatsapp/message/send/request",
            to="554899998888",
            body="Test Message!")
```

I made this as a test couple months ago, but I think it still works. 
If this code looks strange to you, please first check some examples on pub/sub with RabbitMQ first.
Any problems, just ask!

**Comment by x23piracy** [comment]
Hi,

i get: ImportError: No module named rabbitmq.rabbitmq_layer
Is there maybe something missing?


Regards X23

**Comment by x23piracy** [comment]
Hi,

please help me with this, i have problems to get this running.


Regards X23

**Comment by montemarcaldera** [comment]
@x23piracy Try installing the module with ´´´ sudo pip install pika ´´´

**Comment by x23piracy** [comment]
Hi,

pika has been already installed.
Is my integration correct? See my post above, i think maybe some steps missing in joaoricardo000 post? Can someone try this also please?


Regards X23

**Comment by montemarcaldera** [comment]
In the layer script you have ```python self.connection = pika.BlockingConnection(pika.ConnectionParameters(config.rabbitmq["localhost"])) ``` but in the joaoricardo000's post, is a bit different ```python self.connection = pika.BlockingConnection(pika.ConnectionParameters(config.rabbitmq["host"]))```

**Comment by x23piracy** [comment]
Hi,

sorry for the confusion while i was trying making it run i thougth this is the hostname rabbitmq connects to, therefore i changed to localhost for a test away from host but in both cases error :) or :(


Regards X23

**Comment by joaoricardo000** [comment]
Almost there...

self.connection = pika.BlockingConnection(pika.ConnectionParameters(**config.rabbitmq["host"]**))

Either add on config.py a new libe for rabbitmq config, like this:

rabbitmq = {"host":"localhost"}

or just replace it

self.connection = pika.BlockingConnection(pika.ConnectionParameters(**"localhost"**))

Good luck!

**Comment by x23piracy** [comment]
Hi,

Like i said also if i change this i get error, please see my posts above.

Could you give me a step by step howto integrate this solution please.


Regards X23

**Comment by joaoricardo000** [comment]
Yes, I read your posts...  

**AttributeError: 'module' object has no attribute 'rabbitmq'**

This was the last error you complained about, and that still the solution.
About problems with RabbitMQ, I strongly advise you to practice and study a little bit more on examples about how to listen and receive messages, on simple test scripts. There is a bunch of tutorials about RabbitMQ + python, and while you don't feel comfortable with it, integrating this on the bot will not be simple...

Good luck..

**Comment by x23piracy** [comment]
Hi,

ok i have the bot now starting up with no errors. When i was rude, i was overliking your post and i was a little bit blind because you already gave me the solution. Sorry for this.

Well since the bot starts no without error i created your example script to send a test message, changed the number to my cell phone number and executed the script:

`root@NbI-1527:/tmp# python test.py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    body="Test Message!")
TypeError: basic_publish() got an unexpected keyword argument 'to'`

Is a code change needed?


Regards X23

**Comment by x23piracy** [comment]
Hi,

i've got rabbitmq working but for your send example i had to remove 'to' and hardcoded recipient within server.py. Now i can send messages but i have to figure out how can i embed the 'to' if not i will abuse the body for message and recipient and split the string before processing.


Regards X23

**Comment by joyarzun** [comment]
Hi there
Now I make me sometime to read the examples and doc for RabbitMQ. Finally I figure out that is too complicate for my needs. It required to run a server of rabbit only for messaging. I expect something more simple, for example, communication between process with multiprocessing library as explain in http://stackoverflow.com/a/6921402
In simple, you send a msg and other process is waiting for him. My problem is how to the waiter process is mix with stack or layer of yosuw. I supposes, your example make a thread that wait for msg and don't interrupt the stack.start() cycle. Then when arrive a msg, the thread call a function in the cycle's stack that trigger a wzp msg, and all happy.
Well my english sucks as usual.

Regards

**Comment by joaoricardo000** [comment]
@x23piracy Hi,
I updated my above example above. 
Just send a json as string on the body message, and when received, parse json to dict and problem solved!

@joyarzun 
Yes, communicating between process works ok, and you don't have to install nothing.
But messaging is so much usefull! Think about the possibilities! You can have 100 bots running, and all of them subscribing the same queue. Other processes in different machines (and languages) could send a request to it with no problem!
And yeah, probably overkill to what you asked haha
But glad you did what you wanted!

**Comment by x23piracy** [comment]
@joaoricardo000 Thank you for the code change (you are missing the closing ")").
I Changed it and gave it a try but no luck but also no error...strange.

When starting the bot:
`_blocking_connection.py_        [INFO][2016-02-05 01:35:38,684] Created channel=1`

Then when i execute the example:
it just executes the script no error but also no message via whatsapp.

Is only the international number needed or is it needed to attach @s.whatsapp.net?


Regards X23
