### ISSUE TITLE
AuthError: not-authorized

### ISSUE THREAD

**Issue by spkprav** [joaoricardo000/whatsapp-bot-seed#29]
Hi, When I use yowsup-cli directly in console, it works fine, after I add the credentials to the config file, I am getting this error.

````
File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/auth/layer_authentication.py", line 77, in handleFailure

raise AuthError(nodeEntity.getReason())

AuthError: not-authorized
````

Any idea?

**Comment by x23piracy** [comment]
Hi,

As far as i know you habe to register it anyway. Iam not sure but think you cannot use both, yowsup and bot at the same time.

When registering with bot it takes some time to generate keys i don't think its possible to register with yowsup and then use crendetials with bot without reregistering.

Regards X23

**Comment by spkprav** [comment]
Hi Thanks for the response. I just resolved it.

Updating yowsup2 from 2.4.2 to 2.4.48 solved the issue, I read that the old version is having auth issue.

**Comment by x23piracy** [comment]
Hi,

how have you updated? npm install yowsup?

When registering with the six digit code, do you use xxx-xxx or xxxxxx?

I have a blocked number, i think because i tried to auth with xxx-xxx it think thats wrong.


Regards X23

**Comment by spkprav** [comment]
Hi, no all credentials are fine. I have already registered to WhatsApp and I have the credentials. Yowsup is having issues with older versions even if the credentials are right. The newer version 2.4.48 will not give any credential issues.

Please update the version in `opt/requirements.pip` to `2.4.48` or I will send you a pull request by tomorrow.

**Comment by montemarcaldera** [comment]
@x23piracy Type in the terminal ´´´ sudo pip install yowsup2 --upgrade ´´´ to upgrade Yowsup easily

**Comment by joaoricardo000** [comment]
Updated on requirements!
