### ISSUE TITLE
howto determine if someone sends over a group or direct?

### ISSUE THREAD

**Issue by x23piracy** [joaoricardo000/whatsapp-bot-seed#30]
Hi,

for some scripting i need to know if someone sends something to the bot via group or direct.
How is that possible?

Regards X23

**Comment by montemarcaldera** [comment]
```python
message.isGroupMessage()
```

**Comment by x23piracy** [comment]
Hi,

thank you :)
and if detected as true howto send the answer not to the group but to the contact directly instead?


Regards X23

**Comment by montemarcaldera** [comment]
message.getParticipant()

**Comment by x23piracy** [comment]
print message.getParticipant() is empty, is getParticipant() really working?

**Comment by Sunil02324** [comment]
Hi,

How to check whether the message is from specific number?
I was try
if (messgae.getParticipant() == '919800116113')

but it is not working

Thanks.

**Comment by x23piracy** [comment]
Hi,

you need to check for number@s.whatsapp.net ;)


Regards X23
