### ISSUE TITLE
Filter groups and admins how does it work?

### ISSUE THREAD

**Issue by x23piracy** [joaoricardo000/whatsapp-bot-seed#33]
Hi,

in config there is this option:

filter_groups = False
admins = ["XXXXXXXXXXXX", ]

If filter_groups is True, the bot only stays
at groups that there is at least one admin on it.
Otherwise will leave instantly if added.

When True the bot will leave any group where the last admin has left?
What about admins = ? is the bot unable to detect natively who is a group admin? 
Should i enter my WA "display name"?
What if it contains spaces?
And can i enter multiple admins like ["the admin1", "the admin2"]?

Regards X23

**Comment by joaoricardo000** [comment]
Hi, 
No, the bot right now will not leave the group if the last admin left.
Yes, you can add multiple admins, with full phone number, not display name. Ex: ['554899998888', '554899887777']
