### ISSUE TITLE
How can i send stored images (from the system where the bot is running)?

### ISSUE THREAD

**Issue by x23piracy** [joaoricardo000/whatsapp-bot-seed#36]
Hi,

i would like to send an image before sending the text answer:
return TextMessageProtocolEntity("text", to=message.getFrom())

How can i do this?

Regards X23

**Comment by joaoricardo000** [comment]
Check src/utils/media_sender.py.
It is simple as that:
```python
image_sender = ImageSender(interface_layer)
image_sender.send_by_path(jid=<userjid>, path="/absolute/path/img.png", caption="optional caption")
```

**Comment by x23piracy** [comment]
Hi,
 how can i use this within: super_views.py?

i added in imports:
ImageSender

and for class superviews:
self.image_sender = ImageSender(self.interface_layer)

    def info(self, message=None, match=None, to=None):
        image_sender = ImageSender(interface_layer)
        image_sender.send_by_path(jid=message.getFrom(), path="/tmp/katze.png", caption="optional caption")
        return TextMessageProtocolEntity(ABOUT_TEXT, to=message.getFrom())

Does not work:

  File "/opt/whatsapp-bot-seed-master/src/router.py", line 78, in handle_callback
    data = callback(message, match)
  File "/opt/whatsapp-bot-seed-master/src/views/super_views.py", line 59, in info
    image_sender = ImageSender(interface_layer)
NameError: global name 'interface_layer' is not defined

**Comment by x23piracy** [comment]
Hi,

after more study i could make it work, thank you for the assistance.


Regards X23

**Comment by rahulroshan96** [comment]
@x23piracy 

Hi, I am getting the same error, can you please share the code, how u solved it !
