### ISSUE TITLE
Not able to download Youtube Videos

### ISSUE THREAD

**Issue by Sunil02324** [joaoricardo000/whatsapp-bot-seed#41]
When a youtube url is passed the following error is raised

CipherError: Couldn't cipher the signature. Maybe YouTube has changed the cipher algorithm. Notify this issue on GitHub: Could not find JS function '
rr'

**Comment by x23piracy** [comment]
Hi,

if pytube installed?
`pip install pytube`

Regards X23

**Comment by joaoricardo000** [comment]
Hi @Sunil02324,
thats a problem with pytube.
https://github.com/nficano/pytube/issues/88

Looks like they fixed it on the last update, try updating ```pip install -U pytube```

If the problem continue, if you could, try downloading this video with youtube-dl
https://github.com/rg3/youtube-dl

I'm considering change to then, looks like they are more stable, and also download from vimeo and others..
