### ISSUE TITLE
how can i send multiple messages while using time.sleep within one def?

### ISSUE THREAD

**Issue by x23piracy** [joaoricardo000/whatsapp-bot-seed#42]
Hi,

how can i send multiple messages within a def?

```
return Text....(
time.sleep(xx)
return Text....(
```

does not work only the first return will be send.

Regards X23

**Comment by joaoricardo000** [comment]
Hi,
to do this, use the interface_layer.

Ex:
```
self.interface_layer.toLower(TextMessageProtocolEntity("Message...", to=message.getFrom()))
```

no need to return anything then.

**Comment by x23piracy** [comment]
Hi,

works, thank you.


Regards X23

**Comment by rahulroshan96** [comment]
@x23piracy @joaoricardo000  How you have implemented multiple message? Can you show me the code ?

**Comment by montemarcaldera** [comment]
@rahulroshan96 `self.interface_layer.toLower(TextMessageProtocolEntity("Message...", to=message.getFrom()))`

**Comment by rahulroshan96** [comment]
@montemarcaldera  what about the callback function? It give error that interface is not defined and callback function give error?
Can you show me the code ?

**Comment by montemarcaldera** [comment]
@rahulroshan96 Take a look to views/super_views.py
