### ISSUE TITLE
Where to locate the log file?

### ISSUE THREAD

**Issue by x23piracy** [joaoricardo000/whatsapp-bot-seed#44]
Hi,

where can i find the log the bot is writing?

```
# Logging configuration.
# By default only logs the command messages.
# If logging_level set to logging.DEBUG, yowsup will log every protocoll message exchange with server.
import logging

log_format = '_%(filename)s_\t[%(levelname)s][%(asctime)-15s] %(message)s'
logging_level = logging.INFO
```

Well i can start the bot while adding
`> /tmp/bot.log`

but any hints with python log usage will be nice.

Regards X23

**Comment by montemarcaldera** [comment]
The bot doesn't generate a log file, if you want to generate it, you need to use ´´´nohup´´´

**Comment by x23piracy** [comment]
Hi,

i simply added the following at the end of the server.py call:

`> /logpath/log.txt` 


Regards X23
