### ISSUE TITLE
trying to trim strings after command

### ISSUE THREAD

**Issue by e0xify** [joaoricardo000/whatsapp-bot-seed#50]
my python is not well enough to get this done, so maybe someone can help me here.
i want to add a command like "/user 'name here'" and get the stuff between ' ' in a variable.

that i can use it for other things.
i dont know where to add this, the commands are defined in the "super_views.py" thats fine, but the bot will fetch messages and waits for a trigger, so i need to add it there in someway,

anybody an idea?

thx

**Comment by x23piracy** [comment]
Hi,

i use is to trim username:

`    def nick(self, message=None, match=None, to=None):
	if message.isGroupMessage() == True:
            return TextMessageProtocolEntity("Der festlegen des Namens ist in der Gruppe nicht erlaubt, bitte durch Direktkonversation einstellen.", to=message.getFrom())
	else:
	    if os.path.exists(user + message.getFrom()):
	        nickname = message.getBody()[6:]
                text_file = open(user + message.getFrom(), "w")
                text_file.write(nickname)
                text_file.close()
                return TextMessageProtocolEntity("Bullshit! " + nickname + " von jetzt an sind Sie Private Schneewittchen! Gefällt Ihnen der Name? /Zusage um für den kommenden Spieltag zuzusagen.", to=message.getFrom())
            else:
                return TextMessageProtocolEntity("Abgelehnt, keine Namensänderung ohne Login... Scherzkeks!", to=message.getFrom())`

**Comment by e0xify** [comment]
Hi , dank dir.

Du trimmst ab dem 6 zeichen oder wie seh ich das? ([6:])
und packst das dann in "nickname" ?

die sache ist halt, ich möchte daten nach angabe des users aus einer website ziehen.
dafür brauch ich aber die angabe des users. also /suchenach "peter" brauche ich das peter irgendwie

**Comment by x23piracy** [comment]
Hi,

right i trim after the sixth sign, you will finde the name in the variable username.

If you need to trim later, increase the number 6 to the value you need.


Regards X23

**Comment by e0xify** [comment]
just one more problem, trying to use it in a urllib request

response = urllib2.urlopen("http://google.de/searchq/" + nickname + "/today#bblabla")
any idea?

its not changing the variable to a value.
