### ISSUE TITLE
wildcard commands - mentioned 

### ISSUE THREAD

**Issue by e0xify** [joaoricardo000/whatsapp-bot-seed#51]
Hi all,

is there a way to wildcard a string? so if there is some name like "karsten" in the message, that it will react. something with ? or * 

 ("^karsten*", self.hs)

thanks

**Comment by x23piracy** [comment]
Hi,

> if "blah" not in somestring: 
    continue

**Comment by e0xify** [comment]
allright, thanks... but where to implement that?
this needs to be checked in every message, so i have no idea where to add it...
