### ISSUE TITLE
WhatsApp abandona smartphones BlackBerry

### ISSUE THREAD

**Issue by wbeirigo** [joaoricardo000/whatsapp-bot-seed#52]
João Ricardo, bom dia,

Eu vi esta notícia e como o yowsup é baseado em symbiam fiquei pensando se esta mudança pode inviabilizar este projeto?

http://www.bitmag.com.br/2016/02/whatsapp-abandona-smartphones-blackberry/

**Comment by joaoricardo000** [comment]
Olá Wilson!  
Pois é, pensei o mesmo quando ví a notícia hehe  
  
O maior problema deste projeto com certeza é a dependência do yowsup, que depende da engenharia reversa dos protocolos do Whatsapp (que o pessoal do https://github.com/mgp25/Chat-API faz muito bem)  
Aparentemente não será nenhum problema, pois apesar de agora o yowsup se cadastrar como um symbiam, o Chat-API se cadastra como Android (https://github.com/mgp25/Chat-API/blob/c01b4cf86581ca090adc796c9a63ffcd432508ef/src/Constants.php)

Então deve ser uma mudanca tranquila pro yowsup.

**Comment by wbeirigo** [comment]
João Ricardo, 

Obrigado pela resposta e parabéns pelo excelente projeto!!!
