### ISSUE TITLE
Error: old_version

### ISSUE THREAD

**Issue by denilsonprates** [joaoricardo000/whatsapp-bot-seed#54]
How do I resolve the error below?

```
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version
```

Thank you, wait.

**Comment by slozano95** [comment]
@denilsonprates  You must change the yowsup virtual enviroment to android
check here https://github.com/tgalal/yowsup/pull/1336/files
