### ISSUE TITLE
While in group and recieve a message, crash

### ISSUE THREAD

**Issue by K4CZP3R** [joaoricardo000/whatsapp-bot-seed#55]
Hi, When I add my bot to group and I send normal text message it throws this: http://pastebin.com/tuY7geWC. 

How can i fix this?

**Comment by montemarcaldera** [comment]
You have to go to "/usr/lib/python2.7/" and open the file "asyncore.py"
In the file, find the line 199 and change ```python def loop(timeout=30.0, use_poll=False, map=None, count=None):``` to ```python def loop(timeout=30.0, use_poll=True, map=None , count=None): ```

**Comment by K4CZP3R** [comment]
No, it doesn't work

**Comment by alafanechere** [comment]
It fixed the issue for me !

**Comment by K4CZP3R** [comment]
@alafanechere so, for you groups messages doesn't work too??

**Comment by K4CZP3R** [comment]
I've found https://github.com/tgalal/yowsup/issues/898, this issue is about AsserationError: msg but I can't find solution. https://github.com/tgalal/yowsup/issues/931 this too

**Comment by alafanechere** [comment]
Yes I am in the same situation exactly.
Its due apparently to a new group message encryption `skmsg` that yowsup seems to have some trouble to handle right now... 

I am trying to edit the code to avoid the `Assertion Error` and ignore the message.
Would be happy to hear from you if you succeed in solving this.

**Comment by K4CZP3R** [comment]
For  @montemarcaldera are group messages working :o

**Comment by K4CZP3R** [comment]
I'm going to reinstall everything, and try it

**Comment by K4CZP3R** [comment]
Guys, IT W O R K S!

**Comment by K4CZP3R** [comment]
I just reinstalled my system and installed 

sudo apt-get install python-dateutil
sudo apt-get install python-setuptools
sudo apt-get install python-dev
sudo apt-get install libevent-dev
sudo apt-get install ncurses-dev

git clone git://github.com/tgalal/yowsup.git

and this https://pypi.python.org/pypi/protobuf/2.6.1 and pycrypto

**Comment by K4CZP3R** [comment]
If you want help, cookiemonsterkg@o2.pl on Skype

**Comment by alafanechere** [comment]
Thanks it worked again for me with a bit of fine tuning. 
I still encounter crash when the bot receives several messages in a row:
````
AuthError("Unhandled stream:error node:\n%s" % node)
AuthError: Unhandled stream:error node:
<stream:error>
<xml-not-well-formed>
</xml-not-well-formed>
</stream:error>
````

**Comment by montemarcaldera** [comment]
@alafanechere #34

**Comment by joaoricardo000** [comment]
@K4CZP3R  @alafanechere 
Did you manage to reverse the problem?  I had this issue in a random group, tried to reinstall and everything, but no success..
What exactly did you do?
Thanks!

@montemarcaldera , merged PR. Sorry for taking so long...

**Comment by montemarcaldera** [comment]
For me, it works fine https://github.com/tgalal/yowsup/pull/1336

**Comment by K4CZP3R** [comment]
I'm doing everything on Raspberry Pi. I reinstalled OS and installed everything one more time but I didn't change environment to android

**Comment by montemarcaldera** [comment]
Well, Yowsup is ignoring my messages only via group chat.

**Comment by K4CZP3R** [comment]
Did you changed environment? Dont do this ;)

**Comment by e0xify** [comment]
still crashing for me:

rror: (9, 'Bad file descriptor')                               
_server.py_     [INFO][2016-03-15 15:58:42,092] Restarting..    
_server.py_     [INFO][2016-03-15 15:58:42,092] ################
#####                                                           
_server.py_     [INFO][2016-03-15 15:58:42,092]         Server s
95864                                                           
_server.py_     [INFO][2016-03-15 15:58:42,093] ################
#####                                                           
_server.py_     [ERROR][2016-03-15 15:58:42,093] Unexpected Exce
Traceback (most recent call last):                              
  File "src/server.py", line 38, in start                       
    self.stack.loop(timeout=0.5, discrete=0.5)                  
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py",
    asyncore.loop(*args, **kwargs)                              
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop      
    poll_fun(timeout, map)                                      
  File "/usr/lib/python2.7/asyncore.py", line 145, in poll      
    r, w, e = select.select(r, w, e, timeout)                   
error: (9, 'Bad file descriptor')                               
_server.py_     [INFO][2016-03-15 15:58:42,093] Restarting..    
_server.py_     [INFO][2016-03-15 15:58:42,093] ################
#####^C                                                         
Traceback (most recent call last):                              
  File "src/server.py", line 55, in <module>                    
    server.start()                                              
  File "src/server.py", line 35, in start                       
    logging.info("#" * 50)                                      
  File "/usr/lib/python2.7/logging/__init__.py", line 1614, in i
    root.info(msg, *args, **kwargs)                             
  File "/usr/lib/python2.7/logging/__init__.py", line 1152, in i
    self._log(INFO, msg, args, **kwargs)                        
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _
    self.handle(record)                                         
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in h
    self.callHandlers(record)                                   
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in c
    hdlr.handle(record)                                         
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in ha
    self.emit(record)                                           
  File "/usr/lib/python2.7/logging/__init__.py", line 872, in em
    stream.write(fs % msg)                                      
KeyboardInterrupt

**Comment by montemarcaldera** [comment]
@e0xify  You have to go to `/usr/lib/python2.7/` and open the file `asyncore.py`
In the file, find the line 199 and change `def loop(timeout=30.0, use_poll=False, map=None, count=None):` to `def loop(timeout=30.0, use_poll=True, map=None , count=None):`

**Comment by montemarcaldera** [comment]
@K4CZP3R Ok, i'll try

**Comment by e0xify** [comment]
Did this before but then i got another error something like child Attribute missing.. 

Will post the log tomorrow

**Comment by joaoricardo000** [comment]
https://github.com/tgalal/yowsup/pull/1364/files fixed!

**Comment by joaoricardo000** [comment]
Just added a Dockerfile, that includes all dependencies and also patches with the above correction.  If you have already docker installed, it is the most easy and reliable way to run the bot.
