### ISSUE TITLE
Is the bot running for anyone? 

### ISSUE THREAD

**Issue by e0xify** [joaoricardo000/whatsapp-bot-seed#73]
Hi,  the bot isnt running correctly anymore for a few days. I take the latest stable builds from yowsup Master branch but it is not reacting anymore After running a few hours. Just get stuck. 

If I want to search for an Image with the /i Commands 70% i get an error like-04-15 08:28:17,227] ##################################################
_layer.py_[ERROR][2016-04-15 08:28:17,822] Received message with old counter: 4, 3
_layer.py_[WARNING][2016-04-15 08:28:17,822] Going to send the delivery receipt myself !
_layer.py_[WARNING][2016-04-15 08:28:17,991] Invalid signature!
_router.py_[INFO][2016-04-15 08:28:30,779] (GROUP)[4915142540521@s.whatsapp.net]-[4915142540521-1460655531@g.us]   /i test
_connectionpool.py_[INFO][2016-04-15 08:28:30,791] Starting new HTTPS connection (1): api.datamarket.azure.com
_media_sender.py_[INFO][2016-04-15 08:28:33,158] [Upload progress]d5d3536bd893533e8ccadf7f441c4dc8.jpg => 4915142540521-1460655531@g.us, 50% 
_media_sender.py_[INFO][2016-04-15 08:28:34,159] [Upload progress]d5d3536bd893533e8ccadf7f441c4dc8.jpg => 4915142540521-1460655531@g.us, 100% 
_mediauploader.py_[ERROR][2016-04-15 08:28:34,160] uploadUrl: https://mmi417.whatsapp.net/u/gzsmJVG7yr0hXfD2_kJxm1rUr3QABTCAHrUsAQ/AsZUC3PMtV3h6-IOoD_i9vfldCY7C8tsSp7lYlQpVhQr, result of uploading media has no url
None
_server.py_[ERROR][2016-04-15 08:28:34,767] Unexpected Exception: 'NoneType' object has no attribute 'getChild'
Traceback (most recent call last):
  File "server.py", line 38, in start
    self.stack.loop(timeout=0.5, discrete=0.5)
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 187, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 201, in poll2
    readwrite(obj, flags)
  File "/usr/lib/python2.7/asyncore.py", line 123, in readwrite
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 108, in readwrite
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 444, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 134, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 155, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 192, in 
    self._sendIq(entity, lambda a, b: self.onGetKeysResult(a, b, self.processPendingMessages), self.onGetKeysError)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 643, in onGetKeysResult
    entity = ResultGetKeysIqProtocolEntity.fromProtocolTreeNode(resultNode)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/protocolentities/iq_keys_get_result.py", line 88, in fromProtocolTreeNode
    preKeyId = ResultGetKeysIqProtocolEntity._bytesToInt(preKeyNode.getChild("id").getData())
AttributeError: 'NoneType' object has no attribute 'getChild'
_server.py_[INFO][2016-04-15 08:28:34,769] Restarting..
_server.py_[INFO][2016-04-15 08:28:34,770] ##################################################
_server.py_[INFO][2016-04-15 08:28:34,770] Server started. Phone number: 
_server.py_[INFO][2016-04-15 08:28:34,770] ##################################################

**Comment by K4CZP3R** [comment]
Yes, for me ;)

**Comment by K4CZP3R** [comment]
You have to download wa16 ver

**Comment by e0xify** [comment]
same issue then
