### ISSUE TITLE
/add /kick /ban not working in project

### ISSUE THREAD

**Issue by haxxorsid** [joaoricardo000/whatsapp-bot-seed#79]
**/add /kick /ban** are not working in my project.
I use **/add Number** or **/ban Number** or **/kick Number** while interacting but I cant see neither any log request in terminal nor even BOT reacts to the request. Please help me, there might be **no error i**n the **whatsapp-bot-seed**, it might be a **problem on my side**. So help me solve it.

**Comment by montemarcaldera** [comment]
#4

**Comment by montemarcaldera** [comment]
Group Admin is disables by default, but, if you want to enable it, just go to router.py and change this:
```python
# group admin views disabled by default.
# read the issue on: https://github.com/joaoricardo000/whatsapp-bot-seed/issues/4
# enable on your own risk!
# routes.extend(GroupAdminViews(self).routes)
```
to this:
```python
# group admin views disabled by default.
# read the issue on: https://github.com/joaoricardo000/whatsapp-bot-seed/issues/4
# enable on your own risk!
routes.extend(GroupAdminViews(self).routes)
```
