### ISSUE TITLE
Whats my WhatsApp Login and Password?

### ISSUE THREAD

**Issue by toaskoas** [joaoricardo000/whatsapp-bot-seed#89]
How can i geht my Login and Password to install the bot?

**Comment by heberholanda** [comment]
**Installation**
Install the image handling system dependencies on bash opt/system-requirements.sh
Create a virtualenv and install the requirements pip install -r opt/requirements.pip
**Follow the instructions on src/config.py to get the whatsapp credentials.**
Then just run the server with python src/server.py
