### ISSUE TITLE
Stating reasons for getting blocked often.

### ISSUE THREAD

**Issue by decieved** [joaoricardo000/whatsapp-bot-seed#95]
Greetings,

I've noticed that you've shutdown a decent working code due to WhatsApp detecting that you're using a bot and banning you automatically, you should be notified that your code is full of loop holes which causes WhatsApp to detect whether you're using a Client or a Bot. 

I've browse through some of your code, and I found the Group Administration code quite interesting, messaging, grabbing links, responding to random texts. There are a few important facts that you should compare with a WhatsApp Bot and the Official Client.

These are very simple and easy to follow.

I notice that your code responds to every messages sent to it as a command and you send the receipt tick as a response. That's fine, but sending the read tick isn't very thoughtful and a human-like behavior which WhatsApp obviously detects.

Another is your Group Administration System, if you do attempt to remove a number which isn't on WhatsApp, it'll detect as a error sent to WhatsApp servers, which the Official Client wouldn't do, these flaws which sends a Non-WhatsApp Client / Human behavior to WhatsApp servers gets detected easily.

I've used your code carefully for up to 24 hours without being banned, debugging how the system works, following all client rules, then suddenly decided to send errors to the server by using your code as it was intended then got blocked, here's some reasons to be blocked below.

> Sending messages to unregistered numbers.
> Attempting to remove unregistered/unavailable numbers from WhatsApp Groups.
> Messaging an excessive amount of numbers that's not synced to your WhatsApp or contacts.
> Being added to multiple groups with numbers that's not in your contact list.
> Adding unregistered numbers to WhatsApp Groups
> Not sending "composing" signal to contacts/numbers & groups before replying. (Not important but decent)

And more, very important and easy to fix. So if you were really looking to create an Anti-Detectable WhatsApp bot, you should really be aware of these facts and learn how WhatsApp actually handles Client requests and protocols. Also consider updating to Python3.x!

Regards!

**Comment by ghost** [comment]
Group administration is disabled by default
